### ISSUE TITLE
login component broken?

### ISSUE THREAD

**Issue by gijbelsy** [dshokouhi/hass-neato-custom-component#8] opened 2019-07-01 18:25 UTC
Since the upgrade to HA 0.93 the neato component has issues logging in.
The logs produce the following error

```
2019-07-01 20:11:32 ERROR (MainThread) [homeassistant.setup] Error during setup of component neato_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neato_custom/__init__.py", line 176, in setup
    hass.data[NEATO_LOGIN] = NeatoHub(hass, config[DOMAIN], Account)
KeyError: 'neato'
```

When I use the built-in component I also get errors:

```
2019-07-01 20:23:28 ERROR (MainThread) [homeassistant.setup] Error during setup of component neato
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/neato/__init__.py", line 174, in setup
    hass.data[NEATO_LOGIN] = NeatoHub(hass, config[DOMAIN], Account)
  File "/usr/src/homeassistant/homeassistant/components/neato/__init__.py", line 198, in __init__
    self._hass.data[NEATO_ROBOTS] = self.my_neato.robots
  File "/usr/local/lib/python3.7/site-packages/pybotvac/account.py", line 64, in robots
    self.refresh_robots()
  File "/usr/local/lib/python3.7/site-packages/pybotvac/account.py", line 110, in refresh_robots
    endpoint=robot['nucleo_url']))
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 43, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 226, in service_version
    return self.available_services['houseCleaning']
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 222, in available_services
    return self.state['availableServices']
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 218, in state
    return self.get_robot_state().json()
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 176, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/usr/local/lib/python3.7/site-packages/pybotvac/robot.py", line 62, in _message
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nucleo.neatocloud.com/vendors/neato/robots/GPC43318-3403DE6FB619/messages
```

Did Neato change their login url?

**Comment by gijbelsy** [comment] 2019-07-01 18:26
The URL seems to be up, but the returned json gives me: 

message | "Route not found"

**Comment by dshokouhi** [comment] 2019-07-01 18:28
This custom component has not been kept up to with the latest HA updates.  For the 404 error, are you able to control your botvac using the neato app?  You can try rebooting the botvac to see if the built-in component will work.  Sometimes botvacs need to be rebooted for them to reconnect properly.

**Comment by gijbelsy** [comment] 2019-07-01 18:31
The app works fine... it's the component that's failing to connect.

**Comment by dshokouhi** [comment] 2019-07-01 18:34
I am on 0.95.4 and the built in component is working just fine for me, try rebooting the botvac it may help.  You can also try using the library below and see if you can get the robots state.  If this library does not work you may want to consider creating a bug here to get it resolved.

https://github.com/stianaske/pybotvac

**Comment by dshokouhi** [comment] 2019-07-13 20:19
@gijbelsy can you try the latest code changes in this branch? https://github.com/dshokouhi/hass-neato-custom-component/tree/multiple_floorplans

**Comment by gijbelsy** [comment] 2019-07-13 20:53
I've tested it with the latest version of HA (Hassio). When I invoke the service: neato_custom_cleaning
the following error appears:

```
2019-07-13 22:51:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1911933104] start_cleaning() takes from 1 to 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 121, in handle_call_service
    connection.context(msg))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1150, in async_call
    self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1174, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neato/vacuum.py", line 77, in neato_custom_cleaning_service
    mode, navigation, category, zone, maps)
  File "/config/custom_components/neato/vacuum.py", line 318, in neato_custom_cleaning
    map_id)
TypeError: start_cleaning() takes from 1 to 5 positional arguments but 6 were given
```

Strange thing is that I don't provide 6 arguments:

```
{
  "entity_id": "vacuum.m_o",
  "mode":"2",
  "navigation":"1",
  "category":"4",
  "zone":"Kitchen"
}
```

**Comment by dshokouhi** [comment] 2019-07-13 20:59
@gijbelsy what happens if you include the map name in the service call?

example:
```
{
  "entity_id": "vacuum.m_o",
  "mode":"2",
  "navigation":"1",
  "category":"4",
  "zone":"Kitchen",
  "map":"Home"
}
```

**Comment by dshokouhi** [comment] 2019-07-13 21:14
Did you make sure to update `manifest.json` as well? That contains the new pybotvac version which may better explain the error you got.

**Comment by gijbelsy** [comment] 2019-07-14 06:26
Same error when including the map name.
I downloaded the whole git and copied it into the custom_components folder.
So as long as the manifest.json on git is correct, I should be OK.

When I use the built-in neato component, I don't get the error. But the log responds with 'zone-name' not found. And I'm sure that I use the correct name for that zone.

You mentioned the new version of pybotvac. The native component refers to .0.13, yours to .0.15. Could it be that the issue is related to Hassio not having the latest pybotvac?

**Comment by dshokouhi** [comment] 2019-07-14 08:20
Ok if you are seeing 0.15 when you are using this repo then the manifest.json file is working.  

The issue with the built-in component unable to find the zone name is fixed by the changes here:

https://github.com/dshokouhi/hass-neato-custom-component/blob/multiple_floorplans/neato/vacuum.py#L189-L200

This actually fixes the issue you reported in #4 

I am working on updating home assistant with the above code changes first to allow for multiple zones, so the new pybotvac package won't fix the issue.  The actual issue there is that only the first floorplan zones are being discovered.  

The issue you are seeing is due to the new code changes I am trying to add here

https://github.com/dshokouhi/hass-neato-custom-component/blob/multiple_floorplans/neato/vacuum.py#L306-L318

When I test this branch locally I am able to start the vacuum and clean based on a map name so the error you are seeing I can't reproduce :/

**Comment by gijbelsy** [comment] 2019-07-15 17:59
What system are you testing on? Hassbian, hassio, custom docker image?

**Comment by dshokouhi** [comment] 2019-07-15 18:02
virtual environment install, i have a dev setup here

**Comment by gijbelsy** [comment] 2019-07-15 18:06
My guess is that the problem is Hass-io. So the argument error isn't reproducible on your system?

**Comment by dshokouhi** [comment] 2019-07-15 18:07
it is not reproducible here, there was an issue with some hass.io instances where I had merged a fix to the branch, can you try updating the entire branch again?

**Comment by gijbelsy** [comment] 2019-07-15 18:26
Success! updated the entire branch and the robot is responding now. No error in the logs either.
Testing a zone as we speak. The robot is cleaning the right zone, but the Neato app tells me it's programmed to do 2 zones... I'll check into that.

**Comment by dshokouhi** [comment] 2019-07-15 18:28
ok yea it seems Hass.IO changed the requirements for custom components so this change was necessary.  Glad it is starting to work for you!  Odd that neao tells you its doing 2 zones not sure about that.  How many floorplans and zones do you have setup? on my setup i only have 1 map and a couple zones

**Comment by gijbelsy** [comment] 2019-07-15 18:38
There still might be an issue. I have 2 floorplans, each with multiple zones defined.
Here is the situation:
The last cleaning cycle I started on the same floorplan was for 'Zone 1', this cycle was started with the Neato App, and completed successfully (a few days ago).
Now I requested a cleaning cycle for 'Zone 2', trough Home Assistant.
The robot started cleaning, when I checked the Neato app, it stated 'Zone1 + Zone2'. And the robot indeed is cleaning both zones, not just zone 2 as requested.

**Comment by dshokouhi** [comment] 2019-07-15 18:41
What names are you using for the zones? are they similar across the floorplans?

**Comment by gijbelsy** [comment] 2019-07-15 18:45
No, they are all unique. For the sake of readability I have:
"Zone 1"
"Zone 2"
"Zone 1 + Zone 2" (this is the one chosen when I type in 'Zone 2' for the custom_cleaning map.
"Zone 3"
"Zone 4"

I'll try another zone to see what happens.

**Comment by dshokouhi** [comment] 2019-07-15 18:48
ok yea the code is designed to look for the zone name as mentioned in the neato app.  Since Zone 2 is listed twice the way the code is written it will take the latest zone.  This is by design because we cannot give the user the zone ID (HA did not accept that PR), so to circumvent that we are going by zone name.  You may need to rename the zones here to make sure they dont contain the same name you are trying to clean.

https://github.com/dshokouhi/hass-neato-custom-component/blob/multiple_floorplans/neato/vacuum.py#L299

**Comment by gijbelsy** [comment] 2019-07-15 18:56
Strange behavior over here:
I try to call the custom cleaning service again, and the error of 'Zone not found appears for every zone on the map, including the one that worked earlier.

**Comment by dshokouhi** [comment] 2019-07-15 18:57
Did you just change a zone name in the neato app? I think it takes like 5 min for the integration to update the new map and zone names.

**Comment by gijbelsy** [comment] 2019-07-15 19:01
I didn't change any zone names. 5 mins have past, but still the same issue.
Is there a way to list all the found zones in the log?

**Comment by dshokouhi** [comment] 2019-07-15 19:03
You will need to interact with the pybotvac library to get a list of all the found zones.  I don't think that is doable in hass.io

**Comment by gijbelsy** [comment] 2019-07-15 19:06
unfortunately not... Unless I start it in dev mode, but I need to figure that one out.
Perhaps something like this is doable?
```

            for boundary in self._robot_boundaries['data']['boundaries']:
                _LOGGER.info(
                    "Zone '%s' found for the robot '%s'",
                    boundary['name'], self._name)
                if zone in boundary['name']:
                    boundary_id = boundary['id']
            if boundary_id is None:
                _LOGGER.error(
                    "Zone '%s' was not found for the robot '%s'",
                    zone, self._name)
```

**Comment by dshokouhi** [comment] 2019-07-16 00:00
Yup that code will work :)  however keep in mind that if you did not change anything all we are doing is retrieving data from neato.  If their server has an issue theres not much we can do.  Adding in your logger statement will list all zones found for the robot.

```
019-07-15 16:57:14 INFO (SyncWorker_3) [custom_components.neato.vacuum] Zone 'Hallway' found for the robot 'Mrs. Neato'
2019-07-15 16:57:14 INFO (SyncWorker_3) [custom_components.neato.vacuum] Zone 'Living room' found for the robot 'Mrs. Neato'
2019-07-15 16:57:14 INFO (SyncWorker_3) [custom_components.neato.vacuum] Zone 'Kitchen' found for the robot 'Mrs. Neato'
2019-07-15 16:57:14 ERROR (SyncWorker_3) [custom_components.neato.vacuum] Zone 'testing' was not found for the robot 'Mrs. Neato'
```

If it was working before and you made no changes its possible it will work now.  I think sometimes if we hit neatos servers a bit too much we start running into odd issues until it cools down.  That was why I added the 5 minute delay.  Beforehand the vacuum was updating every second and you can imagine the network strain there :)

**Comment by dshokouhi** [comment] 2019-07-17 23:47
I have a PR submitted to HA that is approved which has most of the code changes in the branch you are using.  The only exception is being able to specify the `map` in `neato_custom_cleaning` service call.  I have also updated the multiple floorplan branch with the review comments so feel free to try out the latest code to see if it resolves your issues :)

**Comment by dshokouhi** [comment] 2019-08-16 19:32
are you still experiencing issues here?

**Comment by dshokouhi** [comment] 2020-07-15 17:22
Going to close this issue now.  If you still face issues after updating to HA 0.113 please open a new issue with the error log so we can properly investigate.

**Closed as completed by dshokouhi** 2020-07-15 17:22 UTC
