### ISSUE TITLE
How to call service with data?

### ISSUE THREAD

**Issue by mike9011** [dshokouhi/hass-neato-custom-component#2] opened 2018-12-06 12:47 UTC
Hi!

Thanks for creating this custom component! 👍 
Can you please tell me how to call the custom service?

At the moment i'm testing the following but it don't succeed;
```
{
  "mode": "2",
  "navigation": "1",
  "category": "4"
}
```

**Comment by dshokouhi** [comment] 2018-12-06 15:38
@mike9011 yes so once you download the code from the custom cleaning branch you need to actually include the name of the vacuum, not the entity ID but the actual friendly name in the service call.

The services tab in HA should also show you exactly what is expected and required: https://github.com/dshokouhi/hass-neato-custom-component/blob/custom_cleaning/vacuum/services.yaml#L135

**Comment by mike9011** [comment] 2018-12-06 23:46
Great! Got it working now! Do you know perhaps if it's possible to let it clean default with category 4 without the use of the custom service? I already tried to change the custom vacuum component to 

Self.robot.start_cleaning(category=4) but that doesn't work. 

Thanks again.

**Comment by dshokouhi** [comment] 2018-12-06 23:55
Well the issue is that if you attempt to clean with that category and you don't have a map then nothing happens.  There is a PR in the main repo to see if we can use the category and default back if we get an error.

https://github.com/stianaske/pybotvac/pull/20

We have to think about all use cases and right now StartCleaning is supposed to behave by default as if you pressed the button to clean.

**Comment by dshokouhi** [comment] 2019-01-07 02:05
hey just a heads up HA version 0.86 should have the category selected and will clean as long as no go lines are available.  I will be closing this issue now unless you run into other problems.  If you have a D7 check out the zone cleaning branch as I am looking for testers there :)

**Closed as completed by dshokouhi** 2019-01-07 02:05 UTC
